frontend:
  image: dexterliu3/frontend
  tag: 216c7f9
  autoscaling:
    averageUtilization: 90
backend:
  image: dexterliu3/backend
  tag: 216c7f9
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
