frontend:
  image: dexterliu3/frontend
  tag: f7588b5
  autoscaling:
    averageUtilization: 90
backend:
  image: dexterliu3/backend
  tag: f7588b5
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
